### ISSUE TITLE
Hide markers when starting a new sequence

### ISSUE THREAD

**Issue by jrdurrant** [jrdurrant/animaltracker#8]
Automatically hide markers when starting a new sequence (on clicking Add Sequence)

**Comment by jrdurrant** [comment]
Should this hide the markers only until the new sequence has been added, or hide them completely (such that you will need to make each sequence visible again individually)?

**Comment by MarcusRowcliffe** [comment]
The latter (set to hidden until such time as that sequence is individually made visible again).
